### ISSUE TITLE
Youtube link seems to be the wrong video: has nothing to do with time zones

### ISSUE THREAD

**Issue by jsupertramp** [trifle/twitterresearch#11]
`Date and time are crucial to almost all kinds of data analysis, but at the same time they are notoriously difficult to handle. There are two major sources of confusion and errors, which correspond to the layers of modifications that are performed to get from an universal reference time to local time: (a) a timezone offset is added to a reference time to get local time and (b) if applicable, a daylight saving offset yields the seasonally correct time. (This presentation on date and time may be helpful: **[http://www.youtube.com/watch?v=ZroB-e4RXmo]).**
When working with twitter, it is crucial to keep two things in mind and separate: The Twitter API always returns date/time in UTC, the universal reference time (no timezone offset, no daylight saving time!). However, depending on your object of study, users will see and use their local time. In many cases, we need to convert the native UTC dates into some other format. Some best practices for handling this are:
- Always store and/or explicitly declare the timezone information of your data
- Convert at the latest possible opportunity`

**Comment by trifle** [comment]
Thanks, good catch @jsupertramp! I wanted to link this video: https://www.youtube.com/watch?v=keUbVvMJeKY - will update that.
