### ISSUE TITLE
Error after one successful week on downloading

### ISSUE THREAD

**Issue by peterjutzeler** [trifle/twitterresearch#13]
Dear all

It's me again with an urgent matter. I was successully downloading the tweets about the World Economic Forum in Davos with the keywords 'wef2018' and 'davos2018'.

After almost one week and approximately 1GB data the datas were not increasing anymore. I am using an ubuntu webserver and two other scripts are running aside on the same server. Is that the problem? 

Does it have to do with the increasing amount of tweets during the WEF?  I am happy if you can help me soon, because the WEF is in it's second day today. 

Big thanx!

<img width="587" alt="screen_error_wef2018" src="https://user-images.githubusercontent.com/22746148/35321775-24a9fa8c-00e8-11e8-9fcc-84d3f3ce830a.png">

**Comment by Millesimus** [comment]
Edited as I had not seen the picture in the mail.

Your error "420" means that you are exceeding the twitter api rate limit which is possibly due to your multiple use of scripts with the same login. (https://stackoverflow.com/questions/13438965/avoid-420s-with-streaming-api)

**Comment by trifle** [comment]
Another thing to watch for is connection dropouts: Are you using a home DSL connection? When you have a daily reconnect, the twitter stream might hang / get disconnected.
Apart from that, you could also implement recurrent reconnects yourself, to be on the safe side.
In any case, maybe renting a cheap VPS cloud server for a few days is the best option.

**Comment by peterjutzeler** [comment]
You are great, dear @Millesimus and @trifle. 

Thank you for the fast help. Now it runs again. The Americans are sleeping at the moment and I stopped one of the scripts. I was dull enough to use the same twitter login on a rpi just for fun - to collect also the tweets about the 'superbowl'. together with the WEF-tweets it were too many. 

I learn every day and hope not to borrow you too much with my questions. But there was a moment of panic this morning :) 

The webserver is already in use. It was not possible to collect tweets longer than 24 h at home. Now I don't touch the system anymore.

Have a nice week!
