### ISSUE TITLE
IrrecoverableStreamException error

### ISSUE THREAD

**Issue by Vix18** [trifle/twitterresearch#15]
Thanks for the tutorial!

I'm having problems getting started. I've entered my tokens in keys.yaml in the main project directory but I keep getting IrrecoverableStreamException Error. The error message is below. (BTW keys.yaml refers to the tokens in a different way to the twitter developer site - I've tried different combinations though and still can't get it to work)

client_key: is this the same as the consumer key?
client_secret: 
resource_owner_key: is this the same as the access token?
resource_owner_secret

Very grateful for your help!

```

In [25]: examples.track_keywords()
ERROR:root:Connection HTTP error 401
-----------------------------------------------------------------------
IrrecoverableStreamException          Traceback (most recent call last)
<ipython-input-25-e0f81e39dd68> in <module>()
----> 1 examples.track_keywords()

~/Desktop/DS/Twitter/twitterresearch/examples.py in track_keywords()
    159     keywords = ["politics", "election"]
    160     stream = streaming.stream(
--> 161         on_tweet=print_tweet, on_notification=print_notice, track=keywords)
    162 
    163 

~/Desktop/DS/Twitter/twitterresearch/streaming.py in stream(on_tweet, on_notification, track, follow)
    167         if stream.status_code != 200:
    168             stream.close()
--> 169             backoff(int(stream.status_code))
    170         try:
    171             for line in stream.iter_lines():

~/Desktop/DS/Twitter/twitterresearch/streaming.py in backoff(errorcode)
    117     elif errorcode in [401, 403, 404, 406, 413, 416]:
    118         logging.error(u"Connection HTTP error {0}".format(errorcode))
--> 119         raise IrrecoverableStreamException
    120     # We don't handle any other errors
    121     else:

IrrecoverableStreamException: 

```

**Comment by Vix18** [comment]
Got it working: I must have had multiples requests going on and so twitter was denying me access.

Thanks again for this excellent tutorial.

**Comment by trifle** [comment]
These are the best bug reports. Thanks for using the tutorial and documenting this!
I guess we could have a global counter for streams, or even better, for credential usage. That would enable more meaningful warnings/errors.

**Comment by trifle** [comment]
Added #16.
