### ISSUE TITLE
find_keyfile() not working

### ISSUE THREAD

**Issue by DK044** [trifle/twitterresearch#2]
Hi, I'm having an issues running the examples part of twitter_auth.py - It always comes up as a StopIteration error when I'm attempting to 'import examples' to run the demonstrations on the Republican Debates

More specifically, when rest.py is imported and calls the authorize method from twitter_auth.py. [ i.e. auth = twitter_auth.authorize() ], it doesn't work for me. Putting the path of my local copy of keys.yaml as a string before (and in place of) the 'find_keyfile' function didn't work either. It is always a StopIteration error... 

I don't understand because the code shouldn't even be reaching the next() operator.... very confused.

**Comment by trifle** [comment]
Hi @dkraynak, thanks for trying our code!
It seems that the code doesn't find your keyfile (`keys.yaml`). The project is currently not a library that you can install and use in any place - it expects to find the file in the project directory. So the easiest thing is to place your `keys.yaml` in the same directory as the .py files. Once you did that, you should be able to use both

```
  import examples
```

as well as

```
  import twitter_auth
  twitter_auth.authorize(filepath="keys.yaml")
```

You can even try that with empty credentials, in which case you'll at least get a different error:

```
  touch keys.yaml
  python
  import examples
  >>> import examples
  Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    File "/Users/p/projects/twitterresearch/examples.py", line 16, in <module>
      import rest
    File "/Users/p/projects/twitterresearch/rest.py", line 52, in <module>
      auth = twitter_auth.authorize()
    File "/Users/p/projects/twitterresearch/twitter_auth.py", line 67, in authorize
      auth_object = OAuth1Session(client_key=keys["client_key"],
  TypeError: 'NoneType' object is not subscriptable
```

If you still get an error from next(), you may be using python 2 - try python version 3 instead.

Does any of this work for you?

**Comment by trifle** [comment]
Fixed: We now throw a somewhat more helpful Exception on a missing keyfile 43faba6040cc61629d5df6058993621288dcf59f

**Comment by DK044** [comment]
Hi thanks for this timely response!
I followed your suggestions and tinkered a bit - ultimately what worked for me was just slightly altering the find_keyfile() function to search for 'keys.yaml.template' once it was in the proper directory. I was very surprised that change had an effect but that is what seems to have done it.

Sorry but now I'm having some trouble with peewee... for some reason the import is not having trouble finding the peewee module. When I go back and try to reinstall ...
  running install

  ... (several creating/copying commands)...

  copying playhouse\test_utils.py -> build\lib.win-amd64-3.5\playhouse
  copying playhouse__init__.py -> build\lib.win-amd64-3.5\playhouse
  running build_ext
  cythoning playhouse/speedups.pyx to playhouse\speedups.c
  building 'playhouse._speedups' extension
  error: Unable to find vcvarsall.bat

---

  Failed building wheel for peewee
  Running setup.py clean for peewee
Failed to build peewee
Installing collected packages: peewee, progress
  Running setup.py install for peewee ... error

Any further advice would be greatly appreciated! thanks

**Comment by trifle** [comment]
Glad you got it working. The peewee issue stems from your Python install. It probably fails to compile the module. I don't have much experience with Windows, you might fare better with using Anaconda Python.

**Comment by trifle** [comment]
Closing since the original issue is resolved.
