### ISSUE TITLE
examples.save_track_keywords() write() argument error

### ISSUE THREAD

**Issue by DK044** [trifle/twitterresearch#3]
Hi - Thanks for your help on the last issue. I have made a few steps forward but I am now having issues with the examples.save_track_keywords() function: 

When run through IPython in the command line, I receive the pre-formatted error message suggested by the exception handling in the streaming.stream() : 

In [2]: import examples
In [3]: examples.save_track_keywords()
ERROR:root:Error! Encountered Exception write() argument must be str, not dict b
ut continuing in order not to drop stream,

.... (1 for each tweet until keyboard interrupt)
## ERROR:root:User stopped program, exiting!

KeyboardInterrupt      

I'm assuming this is referring to the save_tweet() function .... I've tried tinkering with the format of the 'tweet' parameter to put it in string format but that hasn't worked, and neither has changing the write function to  json.dump() 

How to proceed?

**Comment by trifle** [comment]
Thanks for reporting this! We did indeed forget to translate the tweets to something that can be written to a file. Now json.dump handles that and the examples work.
