### ISSUE TITLE
Unicode Issue on Windows Machines when Exporting Top Retweets from Database

### ISSUE THREAD

**Issue by ajungherr** [trifle/twitterresearch#4]
Text export of top retweets from database breaks off because of unicode encoding issues. This cannot be fixed directly on user machines.

**Comment by trifle** [comment]
This might be an unicode decode error while printing status information to console. If there's a traceback with the exception and line number that would be helpful.

**Comment by trifle** [comment]
Added hint in README.md e669dd6.
