### ISSUE TITLE
New Error Arising from deduplicating input in database import

### ISSUE THREAD

**Issue by ajungherr** [trifle/twitterresearch#9]
After the issue "Persistent Error in the use of import.json() #8" a new error emerged when trying to write data into a database. This time the function "deduplicate_lowercase(tags)" runs in an error:

    187     valid = filter(None, l)
    188     lowercase = [e.lower() for e in valid]
    189     if len(valid) != len(lowercase):
    190         logging.warning("The input file had {0} empty lines, skipping those. Please verify that it is complete and valid.".format(len(lowercase) - len(valid)))
    191     deduplicated = list(set(valid))

TypeError: object of type 'filter' has no len()

**Comment by trifle** [comment]
Thanks! In python3, filter is a generator expression that doesn't have a length, so we actually need to make it a list first. Fixed in 4187cf262d71b1e4bed6a80946be6af736c9964e
